"""baseline

Revision ID: 98b1dd9da74b
Revises: 
Create Date: 2026-07-08 10:43:03.906897

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b1dd9da74b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('bot_type', sa.Enum('rag', 'researcher', 'mentor', name='bot_type', native_enum=False, length=32), server_default='rag', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_bots_owner_id'), 'bots', ['owner_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'ready', 'failed', name='document_status', native_enum=False, length=32), server_default='queued', nullable=False),
    sa.Column('size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_bot_id'), 'documents', ['bot_id'], unique=False)
    op.create_index('ix_documents_bot_status', 'documents', ['bot_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_bot_status', table_name='documents')
    op.drop_index(op.f('ix_documents_bot_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_bots_owner_id'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
